//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaTakip.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbHastaKayitEntities4 : DbContext
    {
        public DbHastaKayitEntities4()
            : base("name=DbHastaKayitEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VitalSignMeasurementValues> VitalSignMeasurementValues { get; set; }
        public virtual DbSet<VitalSigns> VitalSigns { get; set; }
    }
}
