//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VitalSignMeasurementValues
    {
        public int VitalBulguODID { get; set; }
        public double OlcumDeğeri { get; set; }
        public bool Status { get; set; }
        public int VitalBulguID { get; set; }
        public int HastaID { get; set; }
        public System.DateTime OlcumZamani { get; set; }
    
        public virtual VitalSigns VitalSigns { get; set; }
    }
}
