//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VitalSigns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VitalSigns()
        {
            this.VitalSignMeasurementValues = new HashSet<VitalSignMeasurementValues>();
        }
    
        public int VitalBulguID { get; set; }
        public string VitalBulguAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VitalSignMeasurementValues> VitalSignMeasurementValues { get; set; }
    }
}
